<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Add Customers Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'accounts.html',
	'resources' => array(
		'checkbox_checked' => 'Selected',
		'checkbox_unchecked' => 'Unselected',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'crf3913@uncw.edu',
		'to' => 'crf3913@uncw.edu'
	),
	'fields' => array(
		'custom_U9224' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'First Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'First Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Last Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Last Name\' is required.',
				'format' => 'Field \'Last Name\' has an invalid email address.'
			)
		),
		'custom_U9237' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Home Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Home Address\' is required.'
			)
		),
		'custom_U9210' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City\' is required.'
			)
		),
		'custom_U9228' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'State',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'State\' is required.'
			)
		),
		'custom_U9241' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Postcode',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Postcode\' is required.'
			)
		),
		'custom_U9205' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Country',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Country\' is required.'
			)
		),
		'custom_U9201' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Custom',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Custom\' is required.'
			)
		),
		'custom_U9220' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Passsword',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Passsword\' is required.'
			)
		),
		'custom_U9216' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Confirm Password',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Confirm Password\' is required.'
			)
		),
		'custom_U9232' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Initial Amount',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Initial Amount\' is required.'
			)
		),
		'custom_U9185' => array(
			'order' => 10,
			'type' => 'radiogroup',
			'label' => 'Radio Button Group',
			'required' => true,
			'optionItems' => array(
				'Checking',
				'Savings',
				'Savings'
			),
			'errors' => array(
				'required' => 'Field \'Radio Button Group\' is required.',
				'format' => 'Field \'Radio Button Group\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
